language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.* COVERAGE=true
  allow_failures:
    - php: 7.0
    - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

phpunit: if [ "$COVERAGE" == true ]; then phpunit --coverage-text; else phpunit; fi
